gOtherText_NewName::
	.string "NEW NAME$"

gNameChoice_Green::
	.string "GREEN$"

gNameChoice_Red::
	.string "RED$"

gNameChoice_Leaf::
	.string "LEAF$"

gNameChoice_Fire::
	.string "FIRE$"

gNameChoice_Gary::
	.string "GARY$"

gNameChoice_Kaz::
	.string "KAZ$"

gNameChoice_Toru::
	.string "TORU$"

gNameChoice_Ash::
	.string "ASH$"

gNameChoice_Kene::
	.string "KENE$"

gNameChoice_Geki::
	.string "GEKI$"

gNameChoice_Jak::
	.string "JAK$"

gNameChoice_Janne::
	.string "JANNE$"

gNameChoice_Jonn::
	.string "JONN$"

gNameChoice_Kamon::
	.string "KAMON$"

gNameChoice_Karl::
	.string "KARL$"

gNameChoice_Taylor::
	.string "TAYLOR$"

gNameChoice_Oscar::
	.string "OSCAR$"

gNameChoice_Hiro::
	.string "HIRO$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALPH$"

gNameChoice_Kay::
	.string "KAY$"

gNameChoice_Tosh::
	.string "TOSH$"

gNameChoice_Roak::
	.string "ROAK$"

gNameChoice_Omi::
	.string "OMI$"

gNameChoice_Jodi::
	.string "JODI$"

gNameChoice_Amanda::
	.string "AMANDA$"

gNameChoice_Hillary::
	.string "HILLARY$"

gNameChoice_Makey::
	.string "MAKEY$"

gNameChoice_Michi::
	.string "MICHI$"

gNameChoice_Paula::
	.string "PAULA$"

gNameChoice_June::
	.string "JUNE$"

gNameChoice_Cassie::
	.string "CASSIE$"

gNameChoice_Rey::
	.string "REY$"

gNameChoice_Seda::
	.string "SEDA$"

gNameChoice_Kiko::
	.string "KIKO$"

gNameChoice_Mina::
	.string "MINA$"

gNameChoice_Norie::
	.string "NORIE$"

gNameChoice_Sai::
	.string "SAI$"

gNameChoice_Momo::
	.string "MOMO$"

gNameChoice_Suzi::
	.string "SUZI$"

gControlsGuide_Text_Intro::
	.string "The various buttons will be explained in\n"
	.string "the order of their importance.$"

gControlsGuide_Text_DPad::
	.string "Moves the main character.\n"
	.string "Also used to choose various data\n"
	.string "headings.$"

gControlsGuide_Text_AButton::
	.string "Used to confirm a choice, check\n"
	.string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
	.string "Used to exit, cancel a choice,\n"
	.string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
	.string "Press this button to open the\n"
	.string "MENU.$"

gControlsGuide_Text_SelectButton::
	.string "Used to shift items and to use\n"
	.string "a registered item.$"

gControlsGuide_Text_LRButtons::
	.string "If you need help playing the\n"
	.string "game, or on how to do things,\n"
	.string "press the L or R Button.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Now tell me. Are you a boy?\n"
	.string "Or are you a girl?$"

gPikachuIntro_Text_Page1::
	.string "In the world which you are about to\n"
	.string "enter, you will embark on a grand\n"
	.string "adventure with you as the hero.\n"
	.string "\n"
	.string "Speak to people and check things\n"
	.string "wherever you go, be it towns, roads,\n"
	.string "or caves. Gather information and\n"
	.string "hints from every source.$"

gPikachuIntro_Text_Page2::
	.string "New paths will open to you by helping\n"
	.string "people in need, overcoming challenges,\n"
	.string "and solving mysteries.\n"
	.string "\n"
	.string "At times, you will be challenged by\n"
	.string "others and attacked by wild creatures.\n"
	.string "Be brave and keep pushing on.$"

gPikachuIntro_Text_Page3::
	.string "Through your adventure, we hope\n"
	.string "that you will interact with all sorts\n"
	.string "of people and achieve personal growth.\n"
	.string "That is our biggest objective.\n"
	.string "\n"
	.string "Press the A Button, and let your\n"
	.string "adventure begin!$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Hello, there!\n"
	.string "Glad to meet you!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is OAK.\p"
	.string "People affectionately refer to me\n"
	.string "as the POKéMON PROFESSOR.\p$"

gOakSpeech_Text_ThisWorld::
	.string "This world…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "…is inhabited far and wide by\n"
	.string "creatures called POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "For some people, POKéMON are pets.\n"
	.string "Others use them for battling.\p"
	.string "As for myself…\p"
	.string "I study POKéMON as a profession.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "But first, tell me a little about\n"
	.string "yourself.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Let's begin with your name.\n"
	.string "What is it?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "Right…\n"
	.string "So your name is {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
	.string "This is my grandson.\p"
	.string "He's been your rival since you both\n"
	.string "were babies.\p"
	.string "…Erm, what was his name now?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "Your rival's name, what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "That's right! I remember now!\n"
	.string "His name is {RIVAL}!\p$"


gText_OakSpeech_NuzlockeChallenge::
	.string "Oh, before we begin…\n"
	.string "There’s something new I’ve been\l"
	.string "researching.\p"
	.string "It’s called the NUZLOCKE CHALLENGE!\p"
	.string "It’s a special way to journey that\n"
	.string "makes your adventure more difficult\l"
	.string "and more meaningful.\p"
	.string "Under these rules, if one of your\n"
	.string "POKéMON faints, it’s considered unable\l"
	.string "to battle and must be released.\p"
	.string "Also, you may only catch the first\n"
	.string "POKéMON you encounter in each area.\p"
	.string "These rules test a TRAINER’s bond\n"
	.string "with their team.\p"
	.string "Every choice matters!\p"
	.string "So, would you like to play the\n"
	.string "NUZLOCKE CHALLENGE?\p"
	.string "$"

gText_OakSpeech_NoNuzlocke::
	.string "That’s quite all right!\p"
	.string "There’s no shame in taking your\n"
	.string "journey at your own pace.\p"
	.string "I’ll leave the NUZLOCKE CHALLENGE\n"
	.string "disabled.\p"
	.string "If you decide you want to take on\n"
	.string "the challenge, you'll need to start\l"
	.string "a new game.\p"
	.string "$"

gText_OakSpeech_YesNuzlocke::
	.string "I see!\n"
	.string "You’re looking for a real challenge!\p"
	.string "I’ll enable the NUZLOCKE CHALLENGE\n"
	.string "for your adventure.\p"
	.string "Take good care of your POKéMON.\n"
	.string "Every one of them will be important!\p"
	.string "$"


gOakSpeech_Text_LetsGo::
	.string "{PLAYER}!\p"
	.string "Your very own POKéMON legend is\n"
	.string "about to unfold!\p"
	.string "A world of dreams and adventures\n"
	.string "with POKéMON awaits! Let's go!$"
